/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smc.View;


import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;

import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Ali
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
           Main.setVisible(true);
        Notfication.setVisible(false);
        NotficationCl.setVisible(false);
        NotficationFr.setVisible(false);
        ShowDate();
        ShowTime();
    }
    

    void ShowDate(){
        Date d=new Date();
        SimpleDateFormat s=new SimpleDateFormat("EEEE dd-MM-YYYY");
       date.setText(s.format(d));
       DateFr.setText(s.format(d));
       DateCl.setText(s.format(d));
       DateSt.setText(s.format(d));
    }
    void ShowTime(){
    new Timer(0,new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e) {
          Date d=new Date();
        SimpleDateFormat s=new SimpleDateFormat("hh:mm:ss");
       Time.setText(s.format(d));
       TimeFr.setText(s.format(d));
       TimeSt.setText(s.format(d));
       TimeCl.setText(s.format(d));
        }
        
    }).start();
                
                
                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Side = new javax.swing.JPanel();
        StockBlock = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        VenteBlock = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ClientsBlock = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FournisseurBlock = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ChargeBlock = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        StatistiqueBlock = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        CloseDash = new javax.swing.JLabel();
        Contenu = new javax.swing.JPanel();
        Main = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        date = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        Vents = new javax.swing.JPanel();
        Stock = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        Supprimer = new javax.swing.JButton();
        Modifier = new javax.swing.JButton();
        Insert = new javax.swing.JButton();
        Nom = new javax.swing.JLabel();
        InputRech = new javax.swing.JTextField();
        Rechercher = new javax.swing.JLabel();
        Notfication = new javax.swing.JLabel();
        DateSt = new javax.swing.JLabel();
        TimeSt = new javax.swing.JLabel();
        Clinets = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        SupprimerCl = new javax.swing.JButton();
        ModifierCl = new javax.swing.JButton();
        InsertCl = new javax.swing.JButton();
        NomCl = new javax.swing.JLabel();
        InputRechCl = new javax.swing.JTextField();
        RechercherbtnCl = new javax.swing.JLabel();
        NotficationCl = new javax.swing.JLabel();
        DateCl = new javax.swing.JLabel();
        TimeCl = new javax.swing.JLabel();
        Fournisseur = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        SupprimerFr = new javax.swing.JButton();
        ModifierFr = new javax.swing.JButton();
        InsertFr = new javax.swing.JButton();
        NomCl1 = new javax.swing.JLabel();
        InputRechFr = new javax.swing.JTextField();
        RechercherbtnFr = new javax.swing.JLabel();
        NotficationFr = new javax.swing.JLabel();
        DateFr = new javax.swing.JLabel();
        TimeFr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));

        Side.setBackground(new java.awt.Color(55, 38, 91));
        Side.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StockBlock.setBackground(new java.awt.Color(85, 65, 118));
        StockBlock.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                StockBlockMouseMoved(evt);
            }
        });
        StockBlock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockBlockMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StockBlockMouseExited(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STOCK");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smc/Images/Stock.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout StockBlockLayout = new javax.swing.GroupLayout(StockBlock);
        StockBlock.setLayout(StockBlockLayout);
        StockBlockLayout.setHorizontalGroup(
            StockBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StockBlockLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        StockBlockLayout.setVerticalGroup(
            StockBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StockBlockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StockBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        Side.add(StockBlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 250, 50));

        VenteBlock.setBackground(new java.awt.Color(85, 65, 118));
        VenteBlock.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                VenteBlockMouseMoved(evt);
            }
        });
        VenteBlock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VenteBlockMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VenteBlockMouseExited(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VENTS");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smc/Images/Vents.png"))); // NOI18N
        jLabel4.setText("jLabel2");

        javax.swing.GroupLayout VenteBlockLayout = new javax.swing.GroupLayout(VenteBlock);
        VenteBlock.setLayout(VenteBlockLayout);
        VenteBlockLayout.setHorizontalGroup(
            VenteBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VenteBlockLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        VenteBlockLayout.setVerticalGroup(
            VenteBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VenteBlockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VenteBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        Side.add(VenteBlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, 50));

        ClientsBlock.setBackground(new java.awt.Color(85, 65, 118));
        ClientsBlock.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ClientsBlockMouseMoved(evt);
            }
        });
        ClientsBlock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientsBlockMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClientsBlockMouseExited(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CLIENTS");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smc/Images/Clients.png"))); // NOI18N
        jLabel6.setText("jLabel2");

        javax.swing.GroupLayout ClientsBlockLayout = new javax.swing.GroupLayout(ClientsBlock);
        ClientsBlock.setLayout(ClientsBlockLayout);
        ClientsBlockLayout.setHorizontalGroup(
            ClientsBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientsBlockLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        ClientsBlockLayout.setVerticalGroup(
            ClientsBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientsBlockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClientsBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        Side.add(ClientsBlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 250, 50));

        FournisseurBlock.setBackground(new java.awt.Color(85, 65, 118));
        FournisseurBlock.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                FournisseurBlockMouseMoved(evt);
            }
        });
        FournisseurBlock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FournisseurBlockMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FournisseurBlockMouseExited(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FOURNISSEUR");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smc/Images/Fournisseur.png"))); // NOI18N
        jLabel8.setText("jLabel2");

        javax.swing.GroupLayout FournisseurBlockLayout = new javax.swing.GroupLayout(FournisseurBlock);
        FournisseurBlock.setLayout(FournisseurBlockLayout);
        FournisseurBlockLayout.setHorizontalGroup(
            FournisseurBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FournisseurBlockLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        FournisseurBlockLayout.setVerticalGroup(
            FournisseurBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FournisseurBlockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FournisseurBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        Side.add(FournisseurBlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 250, 50));

        ChargeBlock.setBackground(new java.awt.Color(85, 65, 118));
        ChargeBlock.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ChargeBlockMouseMoved(evt);
            }
        });
        ChargeBlock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChargeBlockMouseExited(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CHARGE");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smc/Images/Charge.png"))); // NOI18N
        jLabel10.setText("jLabel2");

        javax.swing.GroupLayout ChargeBlockLayout = new javax.swing.GroupLayout(ChargeBlock);
        ChargeBlock.setLayout(ChargeBlockLayout);
        ChargeBlockLayout.setHorizontalGroup(
            ChargeBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChargeBlockLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        ChargeBlockLayout.setVerticalGroup(
            ChargeBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChargeBlockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChargeBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addContainerGap())
        );

        Side.add(ChargeBlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, 50));

        StatistiqueBlock.setBackground(new java.awt.Color(85, 65, 118));
        StatistiqueBlock.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                StatistiqueBlockMouseMoved(evt);
            }
        });
        StatistiqueBlock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StatistiqueBlockMouseExited(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("STATISTIQUE");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smc/Images/Statistique.png"))); // NOI18N
        jLabel12.setText("jLabel2");

        javax.swing.GroupLayout StatistiqueBlockLayout = new javax.swing.GroupLayout(StatistiqueBlock);
        StatistiqueBlock.setLayout(StatistiqueBlockLayout);
        StatistiqueBlockLayout.setHorizontalGroup(
            StatistiqueBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatistiqueBlockLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        StatistiqueBlockLayout.setVerticalGroup(
            StatistiqueBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatistiqueBlockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatistiqueBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        Side.add(StatistiqueBlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 250, 50));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        Side.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 250, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Société Maamoun De Commerce ");
        Side.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smc/Images/logo.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        Side.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 90, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smc/Images/icons8_Logout_Rounded_Up_30px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        CloseDash.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CloseDash.setForeground(new java.awt.Color(54, 33, 89));
        CloseDash.setText("X");
        CloseDash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseDashMouseClicked(evt);
            }
        });

        Contenu.setLayout(new java.awt.CardLayout());

        Main.setBackground(new java.awt.Color(0, 102, 51));
        Main.setForeground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("TEBOULBA");

        date.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("jLabel19");

        Time.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Time.setForeground(new java.awt.Color(255, 255, 255));
        Time.setText("jLabel19");

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(MainLayout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
                .addGap(0, 335, Short.MAX_VALUE)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
                        .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGap(285, 285, 285))
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        Contenu.add(Main, "card5");

        javax.swing.GroupLayout VentsLayout = new javax.swing.GroupLayout(Vents);
        Vents.setLayout(VentsLayout);
        VentsLayout.setHorizontalGroup(
            VentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1017, Short.MAX_VALUE)
        );
        VentsLayout.setVerticalGroup(
            VentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        Contenu.add(Vents, "card4");

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Code Produit", "Libellé", "Code Tva", "Prix unitaire Tva", "Unite", "Type", "Taille", "Remise"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Adresse Livraison");
            jTable1.getColumnModel().getColumn(6).setHeaderValue("Taille");
            jTable1.getColumnModel().getColumn(7).setHeaderValue("Remise");
        }

        jLabel17.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel17.setText("STOCK");

        Supprimer.setBackground(new java.awt.Color(255, 51, 51));
        Supprimer.setText("Supprimer");

        Modifier.setBackground(new java.awt.Color(51, 204, 0));
        Modifier.setText("Modifier");

        Insert.setBackground(new java.awt.Color(153, 153, 0));
        Insert.setText("Insert");
        Insert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsertMouseClicked(evt);
            }
        });

        Nom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Nom.setText("Rechercher");

        InputRech.setText("jTextField1");

        Rechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smc/Images/search.png"))); // NOI18N
        Rechercher.setText("jLabel19");
        Rechercher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RechercherMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RechercherMouseExited(evt);
            }
        });

        Notfication.setForeground(new java.awt.Color(102, 102, 102));
        Notfication.setText("rechercher par code produit et par libélle seulement");

        DateSt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DateSt.setText("jLabel20");
        DateSt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TimeSt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TimeSt.setText("jLabel20");
        TimeSt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout StockLayout = new javax.swing.GroupLayout(Stock);
        Stock.setLayout(StockLayout);
        StockLayout.setHorizontalGroup(
            StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StockLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Notfication, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(377, 377, 377))
            .addGroup(StockLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Nom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputRech, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StockLayout.createSequentialGroup()
                    .addContainerGap(644, Short.MAX_VALUE)
                    .addComponent(DateSt, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(180, 180, 180)))
            .addGroup(StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StockLayout.createSequentialGroup()
                    .addContainerGap(857, Short.MAX_VALUE)
                    .addComponent(TimeSt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        StockLayout.setVerticalGroup(
            StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StockLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StockLayout.createSequentialGroup()
                        .addComponent(Notfication)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputRech, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StockLayout.createSequentialGroup()
                    .addGap(0, 460, Short.MAX_VALUE)
                    .addComponent(DateSt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StockLayout.createSequentialGroup()
                    .addGap(0, 458, Short.MAX_VALUE)
                    .addComponent(TimeSt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Contenu.add(Stock, "card3");

        jTable2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Code Client", "Nom", "Matricule Fiscal", "Adresse Livraison", "Téléphone", "Mode De Paiment"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(2).setHeaderValue("Matricule Fiscal");
        }

        jLabel18.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel18.setText("CLINETS");

        SupprimerCl.setBackground(new java.awt.Color(255, 51, 51));
        SupprimerCl.setText("Supprimer");

        ModifierCl.setBackground(new java.awt.Color(51, 204, 0));
        ModifierCl.setText("Modifier");

        InsertCl.setBackground(new java.awt.Color(153, 153, 0));
        InsertCl.setText("Insert");
        InsertCl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsertClMouseClicked(evt);
            }
        });

        NomCl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NomCl.setText("Rechercher");

        InputRechCl.setText("jTextField1");

        RechercherbtnCl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smc/Images/search.png"))); // NOI18N
        RechercherbtnCl.setText("jLabel19");
        RechercherbtnCl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RechercherbtnClMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RechercherbtnClMouseExited(evt);
            }
        });

        NotficationCl.setForeground(new java.awt.Color(102, 102, 102));
        NotficationCl.setText("rechercher par code client, par nom et matricule fiscal seulement");

        DateCl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DateCl.setText("jLabel20");
        DateCl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TimeCl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TimeCl.setText("jLabel20");
        TimeCl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout ClinetsLayout = new javax.swing.GroupLayout(Clinets);
        Clinets.setLayout(ClinetsLayout);
        ClinetsLayout.setHorizontalGroup(
            ClinetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClinetsLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(NotficationCl, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(371, 371, 371))
            .addGroup(ClinetsLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(NomCl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputRechCl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RechercherbtnCl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InsertCl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ModifierCl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SupprimerCl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(ClinetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ClinetsLayout.createSequentialGroup()
                    .addGap(645, 645, 645)
                    .addComponent(DateCl, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(205, Short.MAX_VALUE)))
            .addGroup(ClinetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClinetsLayout.createSequentialGroup()
                    .addContainerGap(857, Short.MAX_VALUE)
                    .addComponent(TimeCl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        ClinetsLayout.setVerticalGroup(
            ClinetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClinetsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClinetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClinetsLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClinetsLayout.createSequentialGroup()
                        .addComponent(NotficationCl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(ClinetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModifierCl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupprimerCl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InsertCl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RechercherbtnCl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomCl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputRechCl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(ClinetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClinetsLayout.createSequentialGroup()
                    .addGap(0, 458, Short.MAX_VALUE)
                    .addComponent(DateCl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(ClinetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClinetsLayout.createSequentialGroup()
                    .addGap(0, 457, Short.MAX_VALUE)
                    .addComponent(TimeCl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Contenu.add(Clinets, "card3");

        jTable3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Code Fournisseur", "Raison Sociale", "Adresse", "Téléphone", "Fax"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable3.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(jTable3);

        jLabel19.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel19.setText("FOURNISSEUR");

        SupprimerFr.setBackground(new java.awt.Color(255, 51, 51));
        SupprimerFr.setText("Supprimer");

        ModifierFr.setBackground(new java.awt.Color(51, 204, 0));
        ModifierFr.setText("Modifier");

        InsertFr.setBackground(new java.awt.Color(153, 153, 0));
        InsertFr.setText("Insert");
        InsertFr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsertFrMouseClicked(evt);
            }
        });

        NomCl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NomCl1.setText("Rechercher");

        InputRechFr.setText("jTextField1");

        RechercherbtnFr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smc/Images/search.png"))); // NOI18N
        RechercherbtnFr.setText("jLabel19");
        RechercherbtnFr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RechercherbtnFrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RechercherbtnFrMouseExited(evt);
            }
        });

        NotficationFr.setForeground(new java.awt.Color(102, 102, 102));
        NotficationFr.setText("rechercher par code fournisseur et par raison sociale seulement");

        DateFr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DateFr.setText("jLabel20");
        DateFr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TimeFr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TimeFr.setText("jLabel20");

        javax.swing.GroupLayout FournisseurLayout = new javax.swing.GroupLayout(Fournisseur);
        Fournisseur.setLayout(FournisseurLayout);
        FournisseurLayout.setHorizontalGroup(
            FournisseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FournisseurLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(NotficationFr, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(359, 359, 359))
            .addGroup(FournisseurLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(NomCl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputRechFr, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RechercherbtnFr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InsertFr, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ModifierFr, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SupprimerFr, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FournisseurLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DateFr, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TimeFr, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        FournisseurLayout.setVerticalGroup(
            FournisseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FournisseurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FournisseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FournisseurLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FournisseurLayout.createSequentialGroup()
                        .addComponent(NotficationFr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(FournisseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModifierFr, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupprimerFr, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InsertFr, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RechercherbtnFr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomCl1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputRechFr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FournisseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DateFr, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FournisseurLayout.createSequentialGroup()
                        .addComponent(TimeFr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))))
        );

        Contenu.add(Fournisseur, "card3");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(Side, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CloseDash)
                        .addGap(18, 18, 18))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addComponent(Contenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Side, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CloseDash, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseDashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseDashMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseDashMouseClicked

    private void StatistiqueBlockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatistiqueBlockMouseExited
        // TODO add your handling code here:
        StatistiqueBlock.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_StatistiqueBlockMouseExited

    private void StatistiqueBlockMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatistiqueBlockMouseMoved
        // TODO add your handling code here:
        StatistiqueBlock.setBackground(new Color(85,65,100));
    }//GEN-LAST:event_StatistiqueBlockMouseMoved

    private void ChargeBlockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChargeBlockMouseExited
        // TODO add your handling code here:
        ChargeBlock.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_ChargeBlockMouseExited

    private void ChargeBlockMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChargeBlockMouseMoved
        // TODO add your handling code here:
        ChargeBlock.setBackground(new Color(85,65,100));
    }//GEN-LAST:event_ChargeBlockMouseMoved

    private void FournisseurBlockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FournisseurBlockMouseExited
        // TODO add your handling code here:
        FournisseurBlock.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_FournisseurBlockMouseExited

    private void FournisseurBlockMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FournisseurBlockMouseMoved
        // TODO add your handling code here:
        FournisseurBlock.setBackground(new Color(85,65,100));
    }//GEN-LAST:event_FournisseurBlockMouseMoved

    private void ClientsBlockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientsBlockMouseExited
        // TODO add your handling code here:
        ClientsBlock.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_ClientsBlockMouseExited

    private void ClientsBlockMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientsBlockMouseMoved
        // TODO add your handling code here:
        ClientsBlock.setBackground(new Color(85,65,100));
    }//GEN-LAST:event_ClientsBlockMouseMoved

    private void VenteBlockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VenteBlockMouseExited
        // TODO add your handling code here:
        VenteBlock.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_VenteBlockMouseExited

    private void VenteBlockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VenteBlockMouseClicked
        // TODO add your handling code here:
        Vents.setVisible(true);
        Stock.setVisible(false);
        Main.setVisible(false);
        Clinets.setVisible(false);
        Fournisseur.setVisible(false);
    }//GEN-LAST:event_VenteBlockMouseClicked

    private void VenteBlockMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VenteBlockMouseMoved
        // TODO add your handling code here:
        VenteBlock.setBackground(new Color(85,65,100));
    }//GEN-LAST:event_VenteBlockMouseMoved

    private void StockBlockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockBlockMouseExited
        // TODO add your handling code here:
        StockBlock.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_StockBlockMouseExited

    private void StockBlockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockBlockMouseClicked
        // TODO add your handling code here:
        Stock.setVisible(true);
        Main.setVisible(false);
        Vents.setVisible(false);
        Clinets.setVisible(false);
        Fournisseur.setVisible(false);
       
    }//GEN-LAST:event_StockBlockMouseClicked

    private void StockBlockMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockBlockMouseMoved
        // TODO add your handling code here:
        StockBlock.setBackground(new Color(85,65,100));
    }//GEN-LAST:event_StockBlockMouseMoved

    private void RechercherMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherMouseEntered
        // TODO add your handling code here:
       Notfication.setVisible(true);
    }//GEN-LAST:event_RechercherMouseEntered

    private void RechercherMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherMouseExited
        // TODO add your handling code here:
        Notfication.setVisible(false);
    }//GEN-LAST:event_RechercherMouseExited

    private void InsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertMouseClicked
        // TODO add your handling code here:
       

    }//GEN-LAST:event_InsertMouseClicked

    private void InsertClMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertClMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertClMouseClicked

    private void RechercherbtnClMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherbtnClMouseEntered
        // TODO add your handling code here:
        NotficationCl.setVisible(true);
    }//GEN-LAST:event_RechercherbtnClMouseEntered

    private void RechercherbtnClMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherbtnClMouseExited
        // TODO add your handling code here:
        NotficationCl.setVisible(false);
    }//GEN-LAST:event_RechercherbtnClMouseExited

    private void ClientsBlockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientsBlockMouseClicked
        // TODO add your handling code here:
        Clinets.setVisible(true);
        Stock.setVisible(false);
        Main.setVisible(false);
        Vents.setVisible(false);
        Fournisseur.setVisible(false);
    }//GEN-LAST:event_ClientsBlockMouseClicked

    private void FournisseurBlockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FournisseurBlockMouseClicked
        // TODO add your handling code here:
        Fournisseur.setVisible(true);
        Stock.setVisible(false);
        Main.setVisible(false);
        Vents.setVisible(false);
        Clinets.setVisible(false);
       
    }//GEN-LAST:event_FournisseurBlockMouseClicked

    private void RechercherbtnFrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherbtnFrMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_RechercherbtnFrMouseExited

    private void RechercherbtnFrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherbtnFrMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RechercherbtnFrMouseEntered

    private void InsertFrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertFrMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertFrMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChargeBlock;
    private javax.swing.JPanel ClientsBlock;
    private javax.swing.JPanel Clinets;
    private javax.swing.JLabel CloseDash;
    private javax.swing.JPanel Contenu;
    private javax.swing.JLabel DateCl;
    private javax.swing.JLabel DateFr;
    private javax.swing.JLabel DateSt;
    private javax.swing.JPanel Fournisseur;
    private javax.swing.JPanel FournisseurBlock;
    private javax.swing.JTextField InputRech;
    private javax.swing.JTextField InputRechCl;
    private javax.swing.JTextField InputRechFr;
    private javax.swing.JButton Insert;
    private javax.swing.JButton InsertCl;
    private javax.swing.JButton InsertFr;
    private javax.swing.JPanel Main;
    private javax.swing.JButton Modifier;
    private javax.swing.JButton ModifierCl;
    private javax.swing.JButton ModifierFr;
    private javax.swing.JLabel Nom;
    private javax.swing.JLabel NomCl;
    private javax.swing.JLabel NomCl1;
    private javax.swing.JLabel Notfication;
    private javax.swing.JLabel NotficationCl;
    private javax.swing.JLabel NotficationFr;
    private javax.swing.JLabel Rechercher;
    private javax.swing.JLabel RechercherbtnCl;
    private javax.swing.JLabel RechercherbtnFr;
    private javax.swing.JPanel Side;
    private javax.swing.JPanel StatistiqueBlock;
    private javax.swing.JPanel Stock;
    private javax.swing.JPanel StockBlock;
    private javax.swing.JButton Supprimer;
    private javax.swing.JButton SupprimerCl;
    private javax.swing.JButton SupprimerFr;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel TimeCl;
    private javax.swing.JLabel TimeFr;
    private javax.swing.JLabel TimeSt;
    private javax.swing.JPanel VenteBlock;
    private javax.swing.JPanel Vents;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
